package install

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// writeServerFiles generates a docker-compose stack for self-hosting game
// servers under <dir>/server. The compose file uses bind mounts relative to
// its own location, so copying/rsyncing the whole install dir to a Linux
// host is enough. Only services for selected (or already-downloaded) games
// are generated. The .env file is written once and never overwritten — it
// holds passwords the user is expected to edit.
func (e *Engine) writeServerFiles(ctx context.Context) (string, error) {
	if !e.opts.ServerFiles {
		return "not selected", nil
	}
	dir := filepath.Join(e.opts.Dir, "server")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}

	wantQW := e.opts.NeedsQuake1Data() || verifyQuake1Data(e.quake1Dir()) == nil
	wantQ3 := e.opts.Quake3 || verifyQuake3Data(e.quake3Dir()) == nil
	if !wantQW && !wantQ3 {
		return "", fmt.Errorf("no game data found in %s — re-run with --dir pointing at an existing Quake install, or also select games to download them", e.opts.Dir)
	}

	compose := composeFile(wantQW, wantQ3)
	if err := os.WriteFile(filepath.Join(dir, "docker-compose.yml"), []byte(compose), 0o644); err != nil {
		return "", err
	}
	envPath := filepath.Join(dir, ".env")
	if _, err := os.Stat(envPath); os.IsNotExist(err) {
		if err := os.WriteFile(envPath, []byte(serverEnv), 0o644); err != nil {
			return "", err
		}
	}
	if err := os.WriteFile(filepath.Join(dir, "README.md"), []byte(serverReadme(wantQW, wantQ3)), 0o644); err != nil {
		return "", err
	}
	e.log(StepServerFiles, "wrote "+dir+"/docker-compose.yml (edit server/.env before deploying)")
	return "", nil
}

// composeFile renders the docker-compose stack.
//
//   - Quake III Arena: florianpiesche/ioquake3-server (multi-arch, actively
//     built from ioquake3 main), mounting the Steam-downloaded baseq3.
//   - QuakeWorld: niclaslindstedt/nquakesv (MVDSV + KTX, the nQuake server
//     package). amd64-only, so the platform is pinned for arm64 hosts. It
//     ships its own shareware content: no pak mount needed, and clients
//     auto-download maps from the server.
func composeFile(qw, q3 bool) string {
	var b strings.Builder
	b.WriteString("# Generated by quakeup. Edit .env for passwords and names.\n")
	b.WriteString("# Run:  docker compose up -d\n")
	b.WriteString("services:\n")
	if q3 {
		b.WriteString(`  quake3:
    image: florianpiesche/ioquake3-server:latest
    restart: unless-stopped
    ports:
      - "27960:27960/udp"
    volumes:
      - ../quake3/baseq3:/opt/quake3/baseq3:ro
    environment:
      SERVER_MOTD: "${Q3_MOTD}"
      ADMIN_PASSWORD: "${Q3_RCON_PASSWORD}"
      SERVER_ARGS: "${Q3_SERVER_ARGS}"
`)
	}
	if qw {
		b.WriteString(`  quakeworld:
    image: niclaslindstedt/nquakesv:latest
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "27500:27500/udp"
    environment:
      HOSTNAME: "${QW_HOSTNAME}"
      PORT: "27500"
      RCON_PASSWORD: "${QW_RCON_PASSWORD}"
      SERVER_ADMIN: "${QW_ADMIN}"
`)
	}
	return b.String()
}

const serverEnv = `# quakeup server settings — edit before deploying.
Q3_MOTD=Welcome to my Quake III server
Q3_RCON_PASSWORD=changeme
Q3_SERVER_ARGS=
QW_HOSTNAME=My QuakeWorld Server
QW_RCON_PASSWORD=changeme
QW_ADMIN=admin <admin@example.com>
`

func serverReadme(qw, q3 bool) string {
	var b strings.Builder
	b.WriteString(`# quakeup servers

Self-hosted game servers via docker-compose. Works on any Docker host;
a small Linux VPS is the typical target.

## Deploy

1. Edit ` + "`.env`" + ` (passwords, server names).
2. ` + "`docker compose up -d`" + `
`)
	if q3 {
		b.WriteString(`
## Quake III Arena (port 27960/udp)

Mounts the Steam-downloaded ` + "`../quake3/baseq3`" + ` read-only, so deploy by
copying the whole quakeup install dir to the host (the game data is licensed
to you — don't publish it, a private server is fine), e.g.:

    rsync -a --exclude steamcmd ~/Games/Quake/ user@vps:quake/

Or run quakeup on the host first: ` + "`quakeup --plain --quake3 --games-only --server-files`" + `.
Connect from ioquake3: ` + "`/connect your.host`" + `
`)
	}
	if qw {
		b.WriteString(`
## QuakeWorld (port 27500/udp)

MVDSV + KTX via the nQuake server package. Needs no game data mounted —
it ships shareware content and clients auto-download maps. amd64 image
(pinned platform; on arm64 hosts it runs emulated).
Connect from ezQuake: ` + "`/connect your.host`" + `

For spectator relay (QTV) and proxy (QWFWD) see https://github.com/nQuake/server-docker.
`)
	}
	b.WriteString(`
## Note on Quake 1 co-op

The QuakeWorld server serves deathmatch for QuakeWorld clients (ezQuake).
vkQuake speaks the NetQuake protocol — for co-op with vkQuake clients,
run an FTEQW server instead (it accepts both protocols).
`)
	return b.String()
}
