package install

import (
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// verifyQuake1Data checks the tree the generated launcher actually uses:
// the 2021 rerelease (which itself bundles the classic id1 paks, both
// mission packs, and Dimension of the Machine).
func verifyQuake1Data(dir string) error {
	for _, rel := range []string{
		filepath.Join("rerelease", "id1", "pak0.pak"),
		filepath.Join("rerelease", "QuakeEX.kpf"),
		filepath.Join("id1", "PAK0.PAK"), // classic tree, for purist ports
	} {
		if err := requireFile(filepath.Join(dir, rel)); err != nil {
			return err
		}
	}
	return nil
}

// verifyQuake3Data requires the complete point-release set, not just pak0:
// pak1–pak8 carry the official patches and are needed for compatibility.
func verifyQuake3Data(dir string) error {
	for i := 0; i <= 8; i++ {
		if err := requireFile(filepath.Join(dir, "baseq3", fmt.Sprintf("pak%d.pk3", i))); err != nil {
			return err
		}
	}
	return nil
}

func requireFile(path string) error {
	fi, err := os.Stat(path)
	if err != nil {
		return fmt.Errorf("missing %s", path)
	}
	if fi.Size() == 0 {
		return fmt.Errorf("empty file %s", path)
	}
	return nil
}

// wire copies Quake 3 data into ioquake3's user directory, seeds the
// vestigial CD key, and writes the launcher scripts.
func (e *Engine) wire(ctx context.Context) (string, error) {
	if !e.opts.EnginesOnly {
		if err := verifyQuake1Data(e.quake1Dir()); err != nil {
			return "", err
		}
		if err := verifyQuake3Data(e.quake3Dir()); err != nil {
			return "", err
		}
	}

	// Quake 3 data → ioquake3 user dir. Always overwrite: SteamCMD's
	// `validate` may have repaired the source, and a stale truncated copy
	// must never survive a rerun.
	if err := verifyQuake3Data(e.quake3Dir()); err == nil {
		if err := os.MkdirAll(e.opts.Q3UserData, 0o755); err != nil {
			return "", err
		}
		paks, _ := filepath.Glob(filepath.Join(e.quake3Dir(), "baseq3", "*.pk3"))
		for _, pak := range paks {
			if err := copyFile(pak, filepath.Join(e.opts.Q3UserData, filepath.Base(pak))); err != nil {
				return "", fmt.Errorf("copying %s: %w", filepath.Base(pak), err)
			}
		}
		e.log(StepWiring, fmt.Sprintf("copied %d pk3 files to %s", len(paks), e.opts.Q3UserData))

		keyPath := filepath.Join(e.opts.Q3UserData, "q3key")
		if _, err := os.Stat(keyPath); os.IsNotExist(err) {
			if err := os.WriteFile(keyPath, []byte(placeholderQ3Key), 0o644); err != nil {
				return "", err
			}
			e.log(StepWiring, "seeded q3key (skips the vestigial 1999 CD-key screen)")
		}
	}

	if err := e.writeLaunchers(); err != nil {
		return "", err
	}
	return "", nil
}

func (e *Engine) writeLaunchers() error {
	vkq := filepath.Join(e.opts.AppsDir, "vkQuake.app", "Contents", "MacOS", "vkquake")
	ioq3 := filepath.Join(e.opts.AppsDir, "ioquake3.app", "Contents", "MacOS", "ioquake3")
	basedir := filepath.Join(e.quake1Dir(), "rerelease")

	q1 := "#!/bin/bash\n" +
		"# Quake 1 (2021 rerelease) via vkQuake. Generated by quakeup.\n" +
		"# Mission packs: -hipnotic | -rogue | -game mg1\n" +
		"exec " + shellQuote(vkq) + " -basedir " + shellQuote(basedir) + " \"$@\"\n"
	q3 := "#!/bin/bash\n" +
		"# Quake III Arena via ioquake3. Generated by quakeup.\n" +
		"exec " + shellQuote(ioq3) + " \"$@\"\n"

	for name, content := range map[string]string{
		"play-quake1.sh": q1,
		"play-quake3.sh": q3,
	} {
		if err := os.WriteFile(filepath.Join(e.opts.Dir, name), []byte(content), 0o755); err != nil {
			return err
		}
	}
	return nil
}

// shellQuote single-quotes s for safe interpolation into generated shell
// scripts, handling embedded single quotes.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	tmp, err := os.CreateTemp(filepath.Dir(dst), ".quakeup-cp-*")
	if err != nil {
		return err
	}
	defer func() {
		tmp.Close()
		os.Remove(tmp.Name())
	}()
	if _, err := io.Copy(tmp, in); err != nil {
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Chmod(tmp.Name(), 0o644); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), dst)
}
